### ISSUE TITLE
[10/28〆]ログアウトした後にログインし直した時に、イベントがリロードされないっぽい

### ISSUE THREAD

**Issue by tomohidemiya** [lcnem/ticket-p2p#114]
多分...w

**Comment by YuKimura45z** [comment]
読んでて自分もおもいましたｗｗｗ
各serviceにpublic async initializeをつくっておいて、homeのlogout内でそれをすべて呼ぶとかにしましょうか？

**Comment by tomohidemiya** [comment]
そうっすよねwww
それで良いと思います。

これちゃんとやらないと墓穴掘るなw
と言うわけでシレッと締め切りを修正！！ww

**Comment by YuKimura45z** [comment]
おそらく完
