### ISSUE TITLE
編集するとき、既存に入力していたものが編集フォームに表示されない

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#116]
<img width="1188" alt="2018-10-27 20 56 23" src="https://user-images.githubusercontent.com/32031454/47603694-c7c72980-da2a-11e8-9846-c5f1037e28bf.png">

**Comment by YuKimura45z** [comment]
うん、修正が必要やなこれは

**Comment by YuKimura45z** [comment]
prompt-dialogのソースみればわかるけど、data.input.valueに現在名いれればよい

**Comment by ryuseikurata** [comment]
やります
