### ISSUE TITLE
名前編集中にprompt-dialog以外をクリックすると、既存の名前が見えなくなって、無名になる

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#117]
<img width="766" alt="2018-10-27 21 05 29" src="https://user-images.githubusercontent.com/32031454/47603821-0f01ea00-da2c-11e8-9d3e-e62e44be8313.png">

**Comment by ryuseikurata** [comment]
<img width="599" alt="2018-10-27 21 06 29" src="https://user-images.githubusercontent.com/32031454/47603832-33f65d00-da2c-11e8-96dc-eb844f284eef.png">

**Comment by YuKimura45z** [comment]
空文字で保存しているということなのでresultのfalseチェックする
