### ISSUE TITLE
スマホだとログイン押してまたログインページに戻る？？

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#124]
![bd9e9c10-6db4-4aba-b018-3edd3ee4485d](https://user-images.githubusercontent.com/32031454/47637515-45ac4180-db9f-11e8-9b65-c92230ba8ef0.png)

**Comment by YuKimura45z** [comment]
いややはりこっちはもんだいなかったぞ

**Comment by YuKimura45z** [comment]
これはなおったんか？結局
