### ISSUE TITLE
同じ名前の区分が生成されるので、uniqのvalidateした方がいい

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#132]
<img width="705" alt="2018-10-31 19 43 05" src="https://user-images.githubusercontent.com/32031454/47783088-37982580-dd45-11e8-96e9-8866fb36fa40.png">

**Comment by YuKimura45z** [comment]
いやそれは正常…
なので名前を定員追加履歴にしたほうがいいかもしれんな

**Comment by ryuseikurata** [comment]
あ、なるほど。
そうですね。追加する感じにした方がいいですね。
んで、新区分の時はuniqですね
