### ISSUE TITLE
使ってないのに無効と表示

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#134]
<img width="619" alt="2018-10-31 19 59 46" src="https://user-images.githubusercontent.com/32031454/47783987-a24a6080-dd47-11e8-928f-3157f83130ae.png">

**Comment by ryuseikurata** [comment]
カメラで読み取った後でも有効
<img width="824" alt="2018-10-31 20 01 43" src="https://user-images.githubusercontent.com/32031454/47784043-ce65e180-dd47-11e8-91e8-f07fdd43eca5.png">

**Comment by YuKimura45z** [comment]
てことはcheckTicketのとこがばぐってるんだね。
レスポンスがUSED_TICKETかINVALID_TICKETかで表示変えるとわかりやすそう。

**Comment by ryuseikurata** [comment]
今回の場合は、request parameter違うというだけでした。
ただ、
多分エラーの出力ってもう一個あって、QR画像から読み取れるのが、NEMアドレスじゃないというやつですね。これも入れた方がいいかと。
検知した変数resultがnemアドレスかどうかのやつは入れといてもいいかも
