### ISSUE TITLE
カメラのエラーハンドリング整える

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#137]
- [ ] USED_TICKET
- [ ] INVALID_TICKET
- [ ] NOT CORRECT QR

**Comment by YuKimura45z** [comment]
3つめ意味不明

**Comment by ryuseikurata** [comment]
NOT CORRECT QR QRがそもそもNEMアドレスを表していない

**Comment by kimurayu45z** [comment]
それはINVALID_TICKETと何が違うのでしょうか
