### ISSUE TITLE
sendRewardのpromptDialog開くとたまにPaymentRequestが呼ばれてる

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#145]
<img width="552" alt="2018-11-03 18 15 50" src="https://user-images.githubusercontent.com/32031454/47950385-d36ba080-df94-11e8-978f-c85bfc6ecbac.png">

**Comment by kimurayu45z** [comment]
原因究明してくれ

**Comment by shrek-kurata** [comment]
出てこないので、とりあえずissueとして残しとく

**Comment by kimurayu45z** [comment]
原因わかった
httpsでないといけないというもの
localではつかえないんだわ。。。

**Comment by kimurayu45z** [comment]
localをhttpsにできるとよいんだがな
