### ISSUE TITLE
使用してるパッケージに脆弱性見つかってるので、バージョンアップしてください。

### ISSUE THREAD

**Issue by kmn** [lcnem/ticket-p2p#147]
詳細はこちら。
https://github.com/lcnem/ticket-p2p/network/alerts

**Comment by YuKimura45z** [comment]
https://github.com/aleixmorgadas/nem-library-ts/issues/62

nem-libraryが依存してしまっているため、issueを投げておきました。

**Comment by kimurayu45z** [comment]
nem-libraryではなくnem-sdkか。
