### ISSUE TITLE
削除機能、思いがけない挙動を防ぐためにpromiseの返り値受け取る前に、表示から消すなりした方が良い

### ISSUE THREAD

**Issue by shrek-kurata** [lcnem/ticket-p2p#159]

**Comment by kimurayu45z** [comment]
どういうことか詳しく

**Comment by kimurayu45z** [comment]
りょうたろうとおなじことをこっちにかいただけ？

**Comment by shrek-kurata** [comment]
はい

**Comment by ryuseikurata** [comment]
<img width="470" alt="2018-11-10 17 06 39" src="https://user-images.githubusercontent.com/32031454/48299070-2ef4db80-e50b-11e8-8f08-673f0f1a04fa.png">
