### ISSUE TITLE
QRスキャンボタン

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/ticket-p2p#41]
返金不可とかぶるし、わかりにくいし、もっとよくするべき
FABはトップページ以外は使わない方針でも良いかもしれんな

**Comment by Dragon-taro** [comment]
dialogの中に表示してもいいのでは？

**Comment by YuKimura45z** [comment]
dialog表示するとしたらどういう文言？

**Comment by ryuseikurata** [comment]
少なくとも、下書き状態の時にQRスキャンボタンを表示せず、
販売開始になったらQRスキャンボタンがわかるようにすることが大事かと

**Comment by YuKimura45z** [comment]
done
