### ISSUE TITLE
枠管理とメール送信システム

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/ticket-p2p#43]
#42
のとおり、
決済はやはり受け持つべきではない。
しかしGASのやっている
・メール送信
・枠の管理
を受け持つシステムはつくったほうがよい。

2層…stripeやステーブルコインによる決済を通じたサイト埋め込み
1層…枠管理とアドレス発行

**Comment by YuKimura45z** [comment]
決済に関しては、チケットに限らずステーブルコインを受け取るモジュール（ようするにpayment request）を広めれば、決済受け持たなくても十分に簡単化可能であるし、ステーブルコインの普及に資する。

**Comment by YuKimura45z** [comment]
コンプラセキュリティコストを抑えるために
・終了したイベントの情報は全破棄
・決済受け持ちはしない

**Comment by YuKimura45z** [comment]
events/{event}
```
{
  name: string,
  nonce: number,
  groups: {
    id: string,
    name: string,
    capacity: number
  }[],
  startAt: Date,
  endAt: Date,
  createdAt: Date,
}
```

events/{event}/purchases/{purchase}
```
{
  group: string,
  address: string,
  profile: {
    name: string,
    email: string,
    phone: string
  },
  reservation: string,//座席情報(A12とかをそのまま格納)
  createdAt: Date,
}
```

events/{event}/capacitySupplements/{capacitySupplement}
```
{
  capacity: number,
  createdAt: Date
}
```

**Comment by YuKimura45z** [comment]
`started`が`null`もしくは`false`の場合は、下書き状態とみなし、編集をうけつける。
それ以降は編集をうけつけない、というようにすると、顧客保護（参加者）にもなるし実装楽だしセキュアかなと思う

**Comment by YuKimura45z** [comment]
`ended`が`false`の場合は、決裁未完了として、改札機能を制限。
使った分だけ支払えるように、イベントチケット販売→改札までに支払うこととする。
`ended`がtrueになると、それ以上は買うことができない。

**Comment by YuKimura45z** [comment]
homeではイベント一覧を表示する
イベントごとに、購入数と定員をグループごと(一般や学生など)に表示

eventページでは、イベント詳細を表示する。
・下書き（イベント名、グループごとの定員）の編集
・下書き状態を終わらせ、販売を開始するボタン
・販売を終了し、使った分だけ支払うボタン
・QRスキャンボタン

これらのUIを考えたい

**Comment by YuKimura45z** [comment]
セキュリティルールは
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{user} {
      allow read, create, update: if request.auth.uid == user;
      
      match /events/{event} {
        allow read, create: if request.auth.uid == user;
        allow update: if resource.data.sellingStarted == false;
        allow delete: if resource.data.sellingEnded == true;
        
        match /purchases/{purchase} {
          allow read: if request.auth.uid == user;
        }
      }
    }
  }
}
```

**Comment by Dragon-taro** [comment]
俺が思った改善すべきUI
- 右下のボタンがわかりにくい（せめてホバーの説明はほしい）
- グラフいる？詳細ページにグラフを乗せたらいい気が
- イベント情報削除はいろいろUIに支障をきたしそう
- 枠追加のいきなり請求される感をなんとかしたい
- てか5人ぐらいは無料にしてもいい気が（あ、でも無限にイベント作られると無料で使われてしまう）
- https://github.com/lcnem/ticket-p2p/issues/43#issuecomment-425703368 は徹底検証しないとこの設計は不安な気がする
- イベントページで購入者のリストが見れるようにしたい（改札を通ったかどうか）
- タイムスタンプってなんだ
- 優先度は低いが主要言語でsdkを作るのはありかも
- 現状のメールを知らないができるだけリッチにして購入者の不安を取り除きたい
- イベント詳細に説明orメモがかけるぐらいの機能はほしい（apiでタイトル＆説明が取得できるのをはやしとくのもありかも？）
- nonceって表現が分かりにくいかも
- チケットに限ったことじゃないけど、メニューのハンバーガーがトップしか表示されないってのはどうなんやろ

**Comment by Dragon-taro** [comment]
> `sellingEnded`が`false`の場合は、決済未完了として、改札機能を制限。
> 使った分だけ支払えるように、イベントチケット販売→改札までに支払うこととするというわけ。
> `true`になると、それ以上は買うことができない。

支払いのタイミングが分からないです、、

**Comment by Dragon-taro** [comment]
クレカの情報持ちたくないけど、毎回支払いを請求されるUXのくそさとのトレードオフ、、
ベストなんはクレカの情報を登録させて、購入されるたびに課金が一番いいんやけどな、、

**Comment by YuKimura45z** [comment]
>右下のボタンがわかりにくい（せめてホバーの説明はほしい）
それな

>グラフいる？詳細ページにグラフを乗せたらいい気が
そう思ってプルリクのコミットでは消えてある

>イベント情報削除はいろいろUIに支障をきたしそう
たしかに慎重になるべきやな、もっと検証しよ

>枠追加のいきなり請求される感をなんとかしたい
枠追加システムを無くすのです

>てか5人ぐらいは無料にしてもいい気が（あ、でも無限にイベント作られると無料で使われてしまう）
うん、無限に作られるのもあるので無料枠はしないでおく

>#43 (comment) は徹底検証しないとこの設計は不安な気がする
検証しよう

>イベントページで購入者のリストが見れるようにしたい（改札を通ったかどうか）
つくってる

>タイムスタンプってなんだ
とりあえず消した

>優先度は低いが主要言語でsdkを作るのはありかも
api叩くだけやしapiの種類1つだけやし流石にいらん気がする

>現状のメールを知らないができるだけリッチにして購入者の不安を取り除きたい
メールは現状ではGASで主催者任せ
メールのhtmlテンプレ編集機能つければ、htmlのリッチなメール送れるようにできそうだな

>イベント詳細に説明orメモがかけるぐらいの機能はほしい（apiでタイトル＆説明が取得できるのをはやしとくのもありかも？）
たしかに

>nonceって表現が分かりにくいかも
コピペするだけやし変えてもあんま影響なさそう（それより変えるコストが、、）

>チケットに限ったことじゃないけど、メニューのハンバーガーがトップしか表示されないってのはどうなんやろ
google純正アプリがすべてこういう挙動やので、これでいいかなと、、

**Comment by YuKimura45z** [comment]
まずイベント情報編集するやろ、定員とかきめるやろ、んでsellingStartedをtrueにする。
するとイベント情報は編集できなくなり、購入APIが有効化される

で、主催者が適当に決めた販売期間が終わった時点で、主催者は販売終了ボタンを押す

そこで使われたアドレスの数だけ請求

支払うと、改札機能が有効化される

**Comment by ryuseikurata** [comment]
> sellingStartedがfalseの場合は、下書き状態とみなし、編集をうけつける。
それ以降は編集をうけつけない、というようにすると、顧客保護（参加者）にもなるし実装楽だしセキュアかなと思う

アラート必須ですね。

**Comment by ryuseikurata** [comment]
UIUI 
# home
- [ ] navigation-tabに「イベント管理ページ」とつける（イベント一覧でもいいかも？）
- [ ] 状態表示はアイコンで
- [ ] イベント開始日、イベント終了日追加

# event
- [ ] navigation-tabにイベント詳細管理をつける
- [ ] dialogで「編集した」あってもいいかも？
- [ ] 販売開始ボタンにdialog(「内容は取り消すことができません。よろしいですか？）を出すべき
- [ ] 状態ごとにUI変えた方がいいかもしれない（例えばQRスキャンボタンは編集の時に入らないのでつけないとか）
- [ ] 万が一、管理者が発行したアドレスに対してトランザクション送ることもなくはないので、デフォルトで、アドレスを表示するのではなく、発行数だけ表示して、アドレス自体はhiddenする

# その他
- [ ] 説明を増やした方がいい
- [ ] コンプラ意識するなら、dialogを必要なところに出すことも必要

**Comment by YuKimura45z** [comment]
あと、メールのテンプレ編集機能だわ、、、

**Comment by YuKimura45z** [comment]
とりあえずだいぶ進んだので残りの個別topicに移行
