### ISSUE TITLE
APIのURL

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/ticket-p2p#45]
各サイトでstripeやステーブルコインの決済処理をしたあと、ちけっとのAPIに名前やメアド電話番号、購入数などを送る必要があるのだが

firebase gcp functionだとus-centralなどごちゃごちゃしたURLになるので、

https://api.ticket-p2p.net/
から転送させたいんだが、なんか方法ないかな

**Comment by ryuseikurata** [comment]
CloudDNSじゃダメなのですか？
https://cloud.google.com/dns/

**Comment by YuKimura45z** [comment]
https://developers-jp.googleblog.com/2017/06/serving-dynamic-content-with-cloud.html?m=1

**Comment by YuKimura45z** [comment]
できたっぽい
