### ISSUE TITLE
販売終了の仕様に関して

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/ticket-p2p#64]
- 販売終了という概念を儲けるべきかどうか
- つければセキュアになるが柔軟性とのトレードオフ

↑あってますか？

**Comment by YuKimura45z** [comment]
せや！

**Comment by YuKimura45z** [comment]
販売終了のメリット
・実装が楽
・とてもセキュア
・逃げられることもない

デメリット
・当日券の対応？
・通報されたぶんの穴埋めとしての発行

**Comment by YuKimura45z** [comment]
穴埋めに関しては、古いチケットアドレスを消して新規に足して、総数が変わらないなら販売終了後もやっていいみたいなのはできるな

問題は当日券

**Comment by YuKimura45z** [comment]
販売終了時に、当日券分を入力させて決済するとか？
