### ISSUE TITLE
develop,test環境の場合、購入時のクレジット処理をスキップさせる

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#87]
# 背景
* デバッグをしたい
* が、クレジット処理で、ちゃんと購入した後の処理が正常にできてるかわからない。

**Comment by YuKimura45z** [comment]
firebase.jsonのりライトがfirebase serveでは効かない問題も含め、なんとかしたいね

**Comment by YuKimura45z** [comment]
あとはpost bodyにenvironment.production? true:falseつけとけば完。
