### ISSUE TITLE
refresh時のメニューバー

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/ticket-p2p#88]
# 概要
* refresh時とafter refreshの位置が違う
* fixedではなくstickyにしてるのが原因
* でもfixedにするとwindowsでおかしくてな
* どっちにするかなやんでる
# 挙動
<img width="1440" alt="2018-10-23 23 24 29" src="https://user-images.githubusercontent.com/32031454/47367761-4d8d6100-d71b-11e8-8d47-e5bf11897f35.png">
<img width="1440" alt="2018-10-23 23 24 34" src="https://user-images.githubusercontent.com/32031454/47367762-4d8d6100-d71b-11e8-89b7-0fc841912969.png">

**Comment by YuKimura45z** [comment]
なおしてpushした
